[package]
name = "tstee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = "4.4.7"
regex="1.10.2"

[profile.release]
codegen-units = 1
lto = "fat"
strip = "debuginfo"